name: Criar Estrutura de Pacote Python

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente para rodar o script

    steps:
    - name: Verificar código do repositório
      uses: actions/checkout@v2

    - name: Configurar o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Defina a versão do Python que você deseja usar

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install setuptools  # Instala o setuptools necessário para o script

    - name: Rodar o script de criação de pacotes
      run: |
        # Extrai o nome do repositório e o nome do autor
        PACKAGE_NAME="${{ github.repository }}"  # Obtém o nome do repositório
        PACKAGE_NAME="${PACKAGE_NAME#*/}"  # Remove o "usuário/" para pegar só o nome do repositório
        AUTHOR="${{ github.actor }}"  # Obtém o nome de usuário do GitHub

        # Rodar o script com o nome do pacote e autor
        python create_package_tree.py $PACKAGE_NAME "$AUTHOR"

